blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),   

    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

    # path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    # path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    # path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>-<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>-<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('api/', include('blog.api.urls', namespace='api')),
    path('api_auth/', include('rest_framework.urls')),
    path('reference/', include('references.urls')),
    path('api_reference/', include('references.api.urls', namespace='apireferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

references/api/urls.py
from django.urls import path
from . import views


app_name = 'references'
urlpatterns = [
    path('references/', views.ReferenceListView.as_view(), name ='api_reference_list'),
]

references/urls.py
from django.urls import path
from . import views

app_name = 'references'

urlpatterns = [
    path('', views.ReferenceListView.as_view(), name='reference_list'),
    path('reference/add/', views.ReferenceCreateView.as_view(), name='reference_create'),
    path('post/<int:pk>/update/', views.ReferenceUpdateView.as_view(), name='reference_update'),
    path('post/<int:pk>/delete/', views.ReferenceDeleteView.as_view(), name='reference_delete'),
]

references/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Reference(models.Model):

    title = models.CharField(max_length = 250)
    description = models.CharField(max_length = 250)
    link = models.URLField(max_length=200)
    author = models.ForeignKey(User,
                                on_delete = models.CASCADE,
                                related_name = 'desc_posts' )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

references/api/views.py
from rest_framework import generics, mixins, permissions
from ..models import Reference
from .serializers import ReferenceSerializer
from django.contrib.auth import get_user_model
from .permissions import IsAuthorOrReadonly
from django.utils.text import slugify


class ReferenceListView(generics.ListCreateAPIView):
    queryset= Reference.objects.all()
    serializer_class = ReferenceSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):   
        if serializer.is_valid():
            serializer.save(author=self.request.user)

references/views.py
from django.shortcuts import render
from .models import Reference
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify

class ReferenceListView(LoginRequiredMixin, ListView):
    queryset = Reference.objects.all()
    context_object_name = 'references'
    paginate_by = 3
    template_name = 'references/reference_list/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ReferenceCreateView(LoginRequiredMixin, CreateView):

    model = Reference
    fields = ['title','description','link']
    template_name = 'references/reference_list/reference_form.html'
    success_url = reverse_lazy('references:reference_list')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class ReferenceUpdateView(LoginRequiredMixin, UpdateView):
    model = Reference
    fields = ['title', 'description', 'link']
    template_name = 'references/reference_list/reference_form.html'
    query_pk_and_slug = True
    success_url = reverse_lazy('references:reference_list')    

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

class ReferenceDeleteView(LoginRequiredMixin, DeleteView):
    model = Reference
    template_name = 'references/reference_list/reference_confirm_delete.html'
    success_url = reverse_lazy('references:reference_list')
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)
    

references/templates/references/reference_list/latest_references.html
<ui>
    {% for reference in latest_references %}
        <li>
                {{ reference.title }}
        </li>
    {% endfor %}
</ui>

references/templates/references/reference_list/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
    Reference
{% endblock title %}

{% block content %}

{% for reference in references %}
    <h2>
        <p>
            {{reference.title}}
            <br>
        </p>

    </h2>
    <p>
        {{reference.description}}
    </p>
        <p>
            <a href="{{reference.link}}">
                {{reference.link}}
            </a>
        </p>
    <p class="date">Published {{reference.publish}}</p>
    <p>
        {% if reference.author == request.user %}

        <a href="{% url 'references:reference_update' reference.id %}">Update Post</a>
        <a href="{% url 'references:reference_delete' reference.id %}">Delete Post</a>

        {% endif %}
    </p>
{% endfor %}

{% include "pagination.html" with page=page_obj %}

{% endblock content %}

references/templates/references/reference_list/reference_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
    Delete Reference
{% endblock title %}

{% block content %}
    <h1>Delete Reference</h1>
    <form action="" method="POST">
        <p>Are you sure want to delete this item <strong>{{ object }}</strong></p>
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
    </form>


{% endblock content %}

references/templates/references/reference_list/reference_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Create / Update
{% endblock title %}


{% block content %}
  <h1>
    {% if 'add' in request.path|slice:'-7:' %}
    Create Reference
    {% else %}
    Update Reference
    {% endif %}
  </h1>  

  <form action="" method="POST">
    {% for field in form %}
            <div class="row">
                <div class="col">
                    {{ field |as_crispy_field }}
                </div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <br>
        <p><input type="submit" 
            value="{% if 'add' in request.path|slice:'-10:' %}Create{% else %}Update{% endif %}" class="btn btn-primary">
          </p>
  </form>
{% endblock content %}