blog/api/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('posts/', views.PostListView.as_view(), name='api_post_list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='api_post_detail'),
    path('users/', views.UserListView.as_view(), name='api_user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='api_user_detail'),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),   

    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

    # path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    # path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    # path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>-<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>-<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('api/', include('blog.api.urls', namespace='api')),
    path('api_auth/', include('rest_framework.urls')),
    path('reference/', include('references.urls')),
    path('api_reference/', include('references.api.urls', namespace='apireferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', blank=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='blog_posts')
    body= models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status =  models.CharField(max_length=10, choices = STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
        return reverse_lazy('blog:post_detail', kwargs={'pk':self.id, 'slug':self.slug})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = 'comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/api/views.py
from rest_framework import generics, mixins, permissions
from ..models import Post
from .serializers import PostSerializer, UserSerializer
from django.contrib.auth import get_user_model
from .permissions import IsAuthorOrReadOnly

# class PostListView(generics.ListAPIView):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

# class PostListView(mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

#     def get(self, request, *args, **kwargs):
#         return self.list(request, *args, **kwargs)

#     def post(self, request, *args, **kwargs):
#         return self.create(request, *args, **kwargs)

class PostListView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        if serializer.is_valid():
            serializer.save(author=self.request.user,
                            status='published',
                            slug=slugify(serializer.validated_data['title'], allow_unicode=True))

# class PostDetailView(generics.RetrieveAPIView):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

# class PostDetailView(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, 
#                         mixins.DestroyModelMixin, generics.GenericAPIView):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

#     def get(self, request, *args, **kwargs):
#         return self.retrieve(request, *args, **kwargs)

#     def put(self, request, *args, **kwargs):
#         return self.update(request, *args, **kwargs)
    
#     def delete(self, request, *args, **kwargs):
#         return self.destroy(request, *args, **kwargs)

class PostDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    #permission----
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]

class UserListView(generics.ListAPIView):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

class UserDetailView(generics.RetrieveAPIView):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify

# Create your views here.
@login_required
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag,])

    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'pages':page, 'posts' : posts, 'tag':tag})

class PostListView(LoginRequiredMixin, ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        tag_slug = self.kwargs.get('tag_slug')

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            qs = qs.filter(tags__in=[tag])
            self.tag = tag
        else:
            self.tag = None
        
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.tag:
            context['tag'] = self.tag
        return context
     

@login_required
def post_detail(request, year, month, day, post):
    # post = get_object_or_404(Post, slug=post, status='published', publish__year = year,
    #                              publish__month = month, publish__day = day)
    # return render(request, 'blog/post/detail.html', {'post':post})

    post = get_object_or_404(Post, slug=post, status='published', publish__year = year,
                                  publish__month = month, publish__day = day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method=='POST':
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4] #slicing 4 teratas

    return render(request, 'blog/post/detail.html', {'post':post, 'comments' : comments, 
                    'new_comment':new_comment, 'comment_form':comment_form, 'similar_posts':similar_posts})


class PostDetailView(LoginRequiredMixin, FormView):
    form_class = CommentForm
    template_name = 'blog/post/detail.html'

    def get_initial(self):
        pk = self.kwargs.get('pk')
        slug = self.kwargs.get('slug')
        self.post = get_object_or_404(Post, pk=pk, slug=slug)

        #list of active comments at that post 
        self.comments = self.post.comments.filter(active = True)
        self.new_comment = None

        #list of similar post
        post_tags_ids = self.post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=self.post.id)
        self.similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

        return super().get_initial()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.post
        context['comments'] = self.comments
        context['similar_posts'] = self.similar_posts
        return context
    
    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.post = self.post
        new_comment.save()
        context = self.get_context_data()
        context['new_comment'] = new_comment
        return render(self.request, self.template_name, context = context)

@login_required
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you to read {post.title}"
            message = (f"Read {post.title} at {post_url}\n\n"
                        f"{cd['name']} comments: {cd['comments']}")
            send_mail(subject, message, 'django.patronus@gmail.com', [cd['to'],])
            sent = True
    else:
        form = EmailPostForm()
    
    return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})

@login_required
def post_search(request):
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # results = Post.published.annotate(search = SearchVector('title','body'),).filter(search=query)
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search = search_vector, 
                                                rank = SearchRank(search_vector, search_query)
                                            ).filter(search=search_query).order_by('-rank')
    else:
        form = SearchForm()
        query = None
        results = []

    return render(request, 'blog/post/search.html', {'form':form, 'query':query, 'results':results})

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['title', 'slug', 'author', 'body', 'tags', 'status']
    fields = ['title', 'body', 'tags']
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.status = 'published'
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)

        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    # fields = ['title', 'slug', 'author', 'body', 'tags', 'status']
    fields = ['title', 'body', 'tags']
    template_name = 'blog/post/post_form.html'
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)
        return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_list')
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    <!-- {{post.body|linebreaks}} -->
    {{post.body|markdown}}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this Post</a>
    </p>

    <!-- similar post -->
    <h2>Similar Posts</h2>
    
    {% for post in similar_posts  %}
        <p>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
        </p>
        <!-- {% if not forloop.last %}, {% endif %} -->
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
        
    <!-- comments -->
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{total_comments|pluralize }}
        </h2>
    {% endwith %}
    
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{forloop.counter}} by {{comment.name}} {{comment.created}} 
            </p>
            {{comment.body|linebreaks}}
        </div>
    {% empty %}
        there are no comments yet
    {% endfor %}
    
    {% if new_comment %}
        <h2>Your Comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="" method="POST">
            <!-- {{comment_form.as_p}} -->
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add Comment"></p>
        </form>
    {% endif %}
        
        

{% endblock content %}
    

blog/templates/blog/post/latest_posts.html
<ul>
    
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
        </li>
    {% endfor %}
        
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    My Blog
{% endblock title %}

{% block content %}
    <h1>My Blog</h1>
    
    {% if tag %}
        <h2>Posts tagged with "{{tag.name}}"</h2>
    {% endif %}
        
    {% for post in posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">
                {{post.title}}
            </a>
        </h2>
        <p class="tags">
            <!-- Tags : {{post.tags.all|join:', '}} -->
            Tags :
            
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{tag.name}}
                </a>
                
                {% if not forloop.last %}, {% endif %}
                    
            {% endfor %}
                
        </p>   
        <p class="date">
            Published {{post.publish}} by {{post.author}}
        </p>
        <!-- {{post.body|truncatewords:30|linebreaks }} -->
        {{ post.body|markdown|truncatewords_html:30 }}
        <p>
            {% if post.author == request.user %}
                <a href="{% url 'blog:post_update' post.id post.slug %}">Update</a> | 
                <a href="{% url 'blog:post_delete' post.id post.slug %}">Delete</a>
            {% endif %}
        </p>
    {% endfor %}

    <!-- {% include "pagination.html" with page=posts %} -->
    {% include "pagination.html" with page=page_obj %}
{% endblock content %}

blog/templates/blog/post/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}
    Delete Post
{% endblock title %}

{% block content %}
    <h1>Delete Post</h1>
    <form action="" method="post">
        <p>Are you sure want to delete this item <strong>{{object}}</strong> ? </p>
        {% csrf_token %}
        <p><input type="submit" value="Confirm Delete"></p>
    </form>
{% endblock content %}
    

blog/templates/blog/post/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create/Update Post
{% endblock title %}

{% block content %}
    <h1>
        {% if 'add' in request.path|slice:'-7:' %}
            Create Post       
        {% else %}
            Update Post
        {% endif %}
    </h1>
    <form action="" method="post">
        <!-- {{form.as_p}} -->
        
        {% for field in form  %}
            <div class="row">
                <div class="col">
                    {{ field|as_crispy_field }}
                </div>
            </div>
        {% endfor %}
            
        {% csrf_token %}
        <br>
        <p>
            <!-- <input type="submit" value="Create/Update"> -->
            <input type="submit" value="{% if 'add' in request.path|slice:'-7:' %}Create{% else %}Update{% endif %}" 
            class="btn btn-primary">
        </p>
    </form>
{% endblock content %}
    

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    Search
{% endblock title %}

{% block content %}
    
    {% if query %}
        <h1>Post containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{total_results}} result{{total_results|pluralize}}
            {% endwith %}   
        </h3>
        
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{post.title}}
                </a>
            </h4>
            {{post.body|markdown|truncatewords_html:5}}
        {% empty %}
            There are no results for your search.
        {% endfor %}
        <p>
            <a href="{% url 'blog:post_search' %}">
                Search Again
            </a>
        </p>  
    {% else %}
        <h1>Search for posts</h1>
        <form action="" method="GET">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
        
{% endblock content %}
    

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
    Share a Post
{% endblock title %}

{% block content %}
    
    {% if sent %}
        <h1>Email succesfully sent</h1>
        <p>
            "{{post.title}}" was succesfully sent to {{form.cleaned_data.to}}
        </p>
    {% else %}
        <h1>Share "{{post.title}}" by email</h1>
        <form action="" method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form>
        
    {% endif %}
        
{% endblock content %}
    
    